### ISSUE TITLE
evdev to read the joystick

### ISSUE THREAD

**Issue by nathany** [nathany/bobblehat#13]
https://gist.github.com/peterhellberg/5a1f66927972587ea3aef24375a1a89d via @peterhellberg

**Comment by peterhellberg** [comment]
We should use a pure Go implementation of evdev, I'm going to see if I can adapt some of the existing implementations (and only support arrow keys + enter)

**Comment by peterhellberg** [comment]
I can probably work on this issue later this week. Do you want me to send PRs or can I commit directly on master?

**Comment by peterhellberg** [comment]
I’m hacking on this issue today :) Will send a PR later today or tomorrow.

**Comment by peterhellberg** [comment]
We should probably bump the Go version to 1.7.1 on Travis-CI
